### ISSUE TITLE
Create a junit5-vintage-consumer module that demonstrates running under JUnit 4

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5-samples#10]
In support of the documentation change described by https://github.com/junit-team/junit5/issues/292.

**Comment by sbrannen** [comment]
The `junit5-maven-consumer` already demonstrates how to execute JUnit Jupiter tests alongside JUnit Vintage tests.

What else did you have in mind?

**Comment by smoyer64** [comment]
It does indeed have both vintage and jupiter tests.  I was envisioning an example that had included a JUnit4 test suite built with @RunWith(JUnitPlatform.class) and @SelectPackages and @SelectClasses as needed but it does seem like a duplication of what's already in this module.  Since these examples are intended to be run via Maven, I had also envisioned examples of how to run the tests from the CLI.

**Comment by sbrannen** [comment]
from the CLI?

Isn't running `mvn clean test` the command line?

Or do you mean you want to see an example project that uses the `ConsoleLauncher`?

**Comment by sbrannen** [comment]
As for including an example suite using `@RunWith(JUnitPlatform.class)`, I think that's a good idea actually.

**Comment by smoyer64** [comment]
Yes ... there were questions (issues) in the junit5 tracker that implied more information was needed on exactly how to run ConsoleLauncher.

**Comment by sbrannen** [comment]
Perhaps you'd like to create an issue or PR to address the `ConsoleLauncher`... ?

**Comment by sbrannen** [comment]
FYI: this is likely the issue you were alluding to: https://github.com/junit-team/junit5/issues/155

**Comment by sormuras** [comment]
2+ years and most build tools and IDEs don't longer require the `@RunWith(JUnitPlatform.class)` mode, as they support the JUnit Platform natively.

About to close this issue. Objections?

**Comment by sbrannen** [comment]
No objection from me.

We just need to get "real" support for suites in the Platform...
