### ISSUE TITLE
Remove 'java' from junit5-jupiter-starter-maven-kotlin

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5-samples#104]
It should, like the `junit5-jupiter-starter-gradle-kotlin` project, only contain the following directories:

_Main_
- `src/main/kotlin`
- `src/test/kotlin`

### Deliverables
- [ ] Remove `java` from` junit5-jupiter-starter-maven-kotlin` sample project.
- [ ] Trim `pom.xml` down to the minimum of configurations needed to get Maven + Kotlin + Jupiter happy.

**Comment by marcphilipp** [comment]
I think the whole point was to have a mixed Java/Kotlin project, wasn‘t it?

**Comment by sormuras** [comment]
Yes. I should have directed it to be what is now described in #105 -- a Java/Kotlin JUnit 4/5 mash up using Maven, it has all a "junit-migration-..." sample project needs.

A `junit5-jupiter-starter-...` should only use the bare minimum to _get started_ with Jupiter a the selected build tool and language.

**Comment by marcphilipp** [comment]
Ah, ok, that makes sense. 👍

**Comment by daggerok** [comment]
Hello, 

please review #106 

---
Regards,
Maksim
