### ISSUE TITLE
Add `junit5-migration-maven-kotlin` sample

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5-samples#105]
# junit5-migration-maven-kotlin

The `junit5-migration-maven-kotlin` project demonstrates how to execute tests written in **Java** and **Kotlin** based on **JUnit 5** using Maven. In addition, it showcases that existing **JUnit 4** based tests can be executed in the same test suite as JUnit Jupiter based tests or any other tests supported on the JUnit Platform.

_Main_
- `src/main/java/.../Calculator.java`
- `src/main/kotlin/.../Kalculator.kt`

_Test_
- `src/test/java/.../CalculatorTests.java`
- `src/test/java/.../JUnit4Test.java`
- `src/test/kotlin/.../KalculatorTests.kt`
- `src/test/java/.../JUnit4Test.kt`

**Comment by daggerok** [comment]
Hi,

please review #107 PR

---
Regards

**Comment by marcphilipp** [comment]
**Team decision:** We think the existing Kotlin starter and migration projects are sufficient and have decided against maintaining another one.
