### ISSUE TITLE
Please cite best practice for not excluding maven-wrapper.jar

### ISSUE THREAD

**Issue by fulldecent** [junit-team/junit5-samples#111]
Regarding this file .mvn/wrapper/maven-wrapper.jar

It is excluded in https://github.com/github/gitignore/blob/master/Maven.gitignore

But not excluded at https://github.com/junit-team/junit5-samples/blob/master/junit5-jupiter-starter-maven/.gitignore

Could reference (blog post, article, documentation, etc.) to a best practice please be provided as to why this choice is made and link added to https://github.com/junit-team/junit5-samples/blob/master/junit5-jupiter-starter-maven/.gitignore

**Comment by sormuras** [comment]
Hi @fulldecent -- this project is about "JUnit 5". Not about GIT and/or best practices regarding when to (not) include some binary files under SCM.

Having said that, the `maven-wrapper.jar` behaves similar to the [Gradle Wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html):

> To make the Wrapper files available to other developers and execution environments you’ll need to check them into version control. All Wrapper files including the JAR file are very small in size. Adding the JAR file to version control is expected. Some organizations do not allow projects to submit binary files to version control. At the moment there are no alternative options to the approach.

Does this answer your question?

**Comment by marcphilipp** [comment]
Apparently contrary to the Gradle wrapper, you can use the Maven wrapper without the JAR:
https://github.com/takari/maven-wrapper#usage-without-binary-jar

**Comment by fulldecent** [comment]
Thank you, much appreciated. These references definitely help me understand what I should be doing. Added the note here https://github.com/github/gitignore/pull/3154 which probably won't be accepted.

Question answered. And I agree, no need to update here to explain why this decision was made.

**Comment by fulldecent** [comment]
Wow it got accepted upstream. Great job.
