### ISSUE TITLE
build.gradle.kts and tag expressions

### ISSUE THREAD

**Issue by soloturn** [junit-team/junit5-samples#144]
its not easy to find out how to run all tests without a tag, plus the ones with a tag flaky, with build.gradle.kts could you add an example or point to one?

**Comment by sbrannen** [comment]
Have you tried using the tag expression `none() | flaky`?

**Comment by marcphilipp** [comment]
Here's a complete example that should work:
```gradle
tasks.test {
    useJUnitPlatform {
        includeTags("none() | flaky")
    }
}
```

Please let us know, if it doesn't.
