### ISSUE TITLE
How to use TestPipeline

### ISSUE THREAD

**Issue by yun-cn** [junit-team/junit5-samples#145]
`  @Rule public final transient TestPipeline pipeline = TestPipeline.create();`

How to write this example in Junit5?
Can you give me some suggest.
Thank you.

**Comment by marcphilipp** [comment]
What's `TestPipeline`?

**Comment by yun-cn** [comment]
This is  Apache beam.

https://beam.apache.org/releases/javadoc/2.0.0/org/apache/beam/sdk/testing/TestPipeline.html

**Comment by marcphilipp** [comment]
Please ask at the Apache Beam project if they (plan to) provide an equivalent JUnit Jupiter extension.
