### ISSUE TITLE
Build fails on JDK 9

### ISSUE THREAD

**Issue by malachid** [junit-team/junit5-samples#15]
While `./gradlew test` works on `junit5-gradle-consumer` if using JDK8; once the user upgrades to JDK9, it breaks:
`Could not create an instance of type com.sun.tools.javac.api.JavacTool.`

The same is not true of junit4.

**Comment by sbrannen** [comment]
> The same is not true of junit4.

What do you mean by that?

In any case, the reason you see `Could not create an instance of type com.sun.tools.javac.api.JavacTool` is that the build is currently using Gradle 2.14.1, and Gradle does not support JDK 9 until Gradle 3.0.

If you run the following, the build will pass on JDK 9.

```
$> ./gradlew wrapper --gradle-version 3.0
$> ./gradlew -version
$> ./gradlew clean test
```
```

Regards,

Sam

**Comment by sbrannen** [comment]
FYI: the build has been upgraded to Gradle 3.0 in 4cc08c271264079e24ac0394baf7288c780be4ea.

Thus, if you `git pull` or create a fresh clone, you should no longer have any issues running the Gradle build on JDK 9. 😉

**Comment by malachid** [comment]
That would explain my confusion. I was using JDK9 + junit4 on my current build, and was trying your test project before upgrading my project -- but I was running on Gradle 3 for my project.

Confirmed runs on JDK9 with fresh pull. Thanks!

**Comment by sbrannen** [comment]
Ahhhhh, yes.... Gradle 3.0 is the secret ingredient.

Glad it all works for you now.
