### ISSUE TITLE
DisplayName tag not working properly in junit5-jupiter-starter-maven example

### ISSUE THREAD

**Issue by Mikolaj6** [junit-team/junit5-samples#159]
Hi,

I've edited CalculatorTests.java file in order for tests to fail:

`assertEquals(2, calculator.add(1, 1), "1 + 1 should equal 2");` to `assertEquals(2, calculator.add(1, 33), "1 + 1 should equal 2");`
and
`"1,  100, 101"` to `"1,  100, 1031"`

However after running  `./mvnw test` I am getting the following output:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------< com.example:junit5-jupiter-starter-maven >--------------
[INFO] Building junit5-jupiter-starter-maven 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ junit5-jupiter-starter-maven ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/mikolaj.grzywacz/IdeaProjects/junit5-samples/junit5-jupiter-starter-maven/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ junit5-jupiter-starter-maven ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ junit5-jupiter-starter-maven ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/mikolaj.grzywacz/IdeaProjects/junit5-samples/junit5-jupiter-starter-maven/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ junit5-jupiter-starter-maven ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ junit5-jupiter-starter-maven ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.example.project.CalculatorTests
[ERROR] Tests run: 5, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.123 s <<< FAILURE! - in com.example.project.CalculatorTests
[ERROR] addsTwoNumbers  Time elapsed: 0.027 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 1 + 1 should equal 2 ==> expected: <2> but was: <34>
        at com.example.project.CalculatorTests.addsTwoNumbers(CalculatorTests.java:26)

[ERROR] add{int, int, int}[4]  Time elapsed: 0.002 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 1 + 100 should equal 1031 ==> expected: <1031> but was: <101>
        at com.example.project.CalculatorTests.add(CalculatorTests.java:38)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   CalculatorTests.addsTwoNumbers:26 1 + 1 should equal 2 ==> expected: <2> but was: <34>
[ERROR]   CalculatorTests.add:38 1 + 100 should equal 1031 ==> expected: <1031> but was: <101>
[INFO] 
[ERROR] Tests run: 5, Failures: 2, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.083 s
[INFO] Finished at: 2021-12-07T19:43:10+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project junit5-jupiter-starter-maven: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/mikolaj.grzywacz/IdeaProjects/junit5-samples/junit5-jupiter-starter-maven/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

As far as I understand DisplayName tag and ParameterizedTest(name=) tag should change: `addsTwoNumbers` to `1 + 1 = 2` and `add{int, int, int}[4]` to `1 +  100 = 1031`, however it seems to have no effect on that part...

Output of `./mvnw --version`:
```
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /Users/myusername/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4
Java version: 1.8.0_282, vendor: Amazon.com Inc., runtime: /Users/myusername/Library/Java/JavaVirtualMachines/corretto-1.8.0_282/Contents/Home/jre
Default locale: pl_PL, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

**Comment by sbrannen** [comment]
That was a known issue that appears to have been addressed in Maven Surefire 3.0.0-M4: https://issues.apache.org/jira/browse/SUREFIRE-1546

You're currently using Surefire 2.22.2.

So you'll have to upgrade to Surefire 3.0.0-M4 or higher (e.g., 3.0.0-M5).

In light of that, I'm closing this issue.

**Comment by sormuras** [comment]
> sunfire

Love it. 🤓 

Maybe one of these help?

https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html#Surefire_Extensions_and_Reports_Configuration_for_.40DisplayName

**Comment by Mikolaj6** [comment]
Now I will remember forever: **SUREFIRE** 😄 

Tried using, parts of and full configuration, but the displayed names stayed the same.

	<plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-surefire-plugin</artifactId>
		<version>3.0.0-M5</version>
		<configuration>
			<statelessTestsetReporter implementation="org.apache.maven.plugin.surefire.extensions.junit5.JUnit5Xml30StatelessReporter">
				<disable>false</disable>
				<version>3.0</version>
				<usePhrasedFileName>false</usePhrasedFileName>
				<usePhrasedTestSuiteClassName>true</usePhrasedTestSuiteClassName>
				<usePhrasedTestCaseClassName>true</usePhrasedTestCaseClassName>
				<usePhrasedTestCaseMethodName>true</usePhrasedTestCaseMethodName>
			</statelessTestsetReporter>
			<consoleOutputReporter implementation="org.apache.maven.plugin.surefire.extensions.junit5.JUnit5ConsoleOutputReporter">
				<disable>false</disable>
				<encoding>UTF-8</encoding>
				<usePhrasedFileName>false</usePhrasedFileName>
			</consoleOutputReporter>
			<statelessTestsetInfoReporter implementation="org.apache.maven.plugin.surefire.extensions.junit5.JUnit5StatelessTestsetInfoReporter">
				<disable>false</disable>
				<usePhrasedFileName>false</usePhrasedFileName>
				<usePhrasedClassNameInRunning>true</usePhrasedClassNameInRunning>
				<usePhrasedClassNameInTestCaseSummary>true</usePhrasedClassNameInTestCaseSummary>
			</statelessTestsetInfoReporter>
		</configuration>
	</plugin>
