### ISSUE TITLE
Alter junit5-maven-consumer POM to demonstrate including and excluding @Tags

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5-samples#18]
When the junit5-platform-surefire-provider is updated by PR https://github.com/junit-team/junit5/pull/485 it will be capable of enabling and disabling tests using include and exclude filters.  Examples of the POM configuration that allows this functionality should be added to the junit5-maven-consumer example (along with tests that conform to the filters).

Please assign this to me as I've got enough code to demonstrate these new capabilities in a feature branch.  With some clean-up, it should meet the JUnit 5 code standards.

**Comment by sbrannen** [comment]
OK, @smoyer64, this is now assigned to you.

**Comment by marcphilipp** [comment]
@smoyer64 We're looking forward to your pull request on this one now. 😄

**Comment by smoyer64** [comment]
Uh-oh ... I hope it's not too anti-climactic!

**Comment by sbrannen** [comment]
Oops... I totally forgot about this issue and went ahead and demonstrated support for excluding tags in 026a9d9abe06b6173398c1a2518793259cd190f2.

Sorry to steal your thunder.

**Comment by smoyer64** [comment]
@sbrannen Don't worry about it ... I got side-tracked by work at the day job and the holidays but hadn't forgotten about it.
