### ISSUE TITLE
junit5-jupiter-starter-gradle  @ParameterizedTest name not displaying

### ISSUE THREAD

**Issue by naresh-gn** [junit-team/junit5-samples#184]
I just checkout this repo and ran `junit5-jupiter-starter-gradle` project using `./gradlew test` and got below output

```
CalculatorTests > 1 + 1 = 2 PASSED

CalculatorTests > add(int, int, int) > com.example.project.CalculatorTests.add(int, int, int)[1] PASSED

CalculatorTests > add(int, int, int) > com.example.project.CalculatorTests.add(int, int, int)[2] PASSED

CalculatorTests > add(int, int, int) > com.example.project.CalculatorTests.add(int, int, int)[3] PASSED

CalculatorTests > add(int, int, int) > com.example.project.CalculatorTests.add(int, int, int)[4] PASSED
```

bottom 4 tests in the above output uses `@ParameterizedTest(name = "{0} + {1} = {2}")` expected test name output should be in  the form of  `"{0} + {1} = {2}"` instead it displays method name.

**Comment by naresh-gn** [comment]
Java version

```
openjdk version "18.0.2" 2022-07-19
OpenJDK Runtime Environment Homebrew (build 18.0.2+0)
OpenJDK 64-Bit Server VM Homebrew (build 18.0.2+0, mixed mode, sharing)
```

**Comment by sbrannen** [comment]
Gradle does not provide support for custom display names.

## Related Issues

- https://github.com/junit-team/junit5/issues/2041
- https://github.com/gradle/gradle/issues/5975

In light of that, I'm closing this issue.
