### ISSUE TITLE
junit5-migration-maven: Upgrade the surefire plugin and remove include patterns

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5-samples#23]
The maven-surefire-plugin version 2.20 includes the "**/*Tests.java" pattern, so the "includes" element can be removed from the plugin's configuration section.

**Comment by smoyer64** [comment]
It will take me about 5 minutes to change and test this (on my home computer) ... assign it to me if you want me to take care of this one.

**Comment by sbrannen** [comment]
Consider yourself _assigned_. 😉

**Comment by sormuras** [comment]
Partly solved via https://github.com/junit-team/junit5-samples/commit/cd7e3b5e8871f72893dd40f76b9346cd23707eb3
Two more `pom.xml` files can't be updated, yet. They need a stable "JUnit 5" release, 5.2.0 I guess.

**Comment by marcphilipp** [comment]
I will update the samples when doing the 5.2 release.

**Comment by marcphilipp** [comment]
Resolved in 1b6f31d0045d3dd85cf4f578606f709b33e01b6b.
