### ISSUE TITLE
Enable snapshot repo for plugins

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-team/junit5-samples#3]
The Maven consumer needs JUnit5-Surefire in version `5.0.0-SNAPSHOT`, which is only available in the snapshot repo. But it is not configured for plugins (only [for regular dependencies](https://github.com/junit-team/junit5-samples/blob/master/junit5-maven-consumer/pom.xml#L19-L32)).

I had to change this ...

```xml
<repositories>
	<repository>
		<id>snapshots-repo</id>
		<!-- snip -->
	</repository>
</repositories>
```
... to this ...

```xml
<pluginRepositories>
	<pluginRepository>
		<id>snapshots-repo</id>
		<!-- snip -->
	</pluginRepository>
</pluginRepositories>
```

... to make `mvn test` work.

**Comment by marcphilipp** [comment]
Good catch, thanks! :+1:
