### ISSUE TITLE
mvnDebug for the junit5-maven-consumer sample doesn't hit breakpoint

### ISSUE THREAD

**Issue by paul-hammant** [junit-team/junit5-samples#30]
One runs `mvnDebug test` and as expected it waits for you to attache a debugger to port 8000.

You go ahead and do that - with a breakpoint set on line 26 of FirstTest.java and it does not land on the breakpoint.

I wasn't expecting full integration with Intellij to be working, but this issue isn't about that, it's about a more basic use: Maven fully in charge of the test site invocation, and Intellij being asked to watch classes being instantiated and pertinent lines to be hit. It is missing them.  Is Junit5 doing something with classloaders that 4.x wasn't previously?

**Comment by marcphilipp** [comment]
Sorry, I have never used `mvnDebug` before. If you just want to debug a test, you can start it in debug mode right from IntelliJ. Why go through Maven?

From what I've just read `mvnDebug` starts the JVM and waits for a debugger to attach to it. However, Maven Surefire will fork that JVM when it launches tests (same for JUnit 4). I'm suspecting that's why you never end up in your breakpoint.

**Comment by paul-hammant** [comment]
Debug mode from Intellij doesn't recognize the JUnit5 bits and pieces. Specifically those in this samples project. I can record a video for you, if you like.  

I was reporting mvDebug because I expect that to work when the above doesn't.   

Maven's surefire is perfectly compatible with what you'd to do in Intellij re debugging a maven project. Both as a right-click action within the IDE, and in partnership with mvnDebug on a pre-agreed JDWP port.

**Comment by sbrannen** [comment]
> Debug mode from Intellij doesn't recognize the JUnit5 bits and pieces. Specifically those in this samples project. I can record a video for you, if you like.

If that's the case, please open an issue against IntelliJ IDEA.

> I was reporting mvDebug because I expect that to work when the above doesn't.

If you feel that there is a bug in the implementation of the Surefire provider for the JUnit Platform, please raise an issue against the `junit5` repository or directly against Maven Surefire since they are taking over the development of the provider.

Thanks!

**Comment by sbrannen** [comment]
Closing this issue since it is not directly related to the sample projects.

**Comment by marcphilipp** [comment]
A short video would be great if it's not too much hassle.

**Comment by paul-hammant** [comment]
Will do

**Comment by paul-hammant** [comment]
Example of IntelliJ not working correctly with the Maven Junit5 sample - https://youtu.be/K_IiyilsEqw

And a second example with mvnDebug in play - https://youtu.be/4qIytxifzX0

What happens for you @marcphilipp ?

**Comment by sormuras** [comment]
@paul-hammant The first video shows a JUnit 5 version clash. IDEA bundles M4 (or older), the sample is already using M5. See http://junit.org/junit5/docs/current/user-guide/#running-tests-ide-intellij-idea for details.

If you add
```xml
<!-- Only required to run tests in an IntelliJ IDEA that bundles an older version -->
<dependency>
    <groupId>org.junit.platform</groupId>
    <artifactId>junit-platform-launcher</artifactId>
    <version>1.0.0-M5</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-engine</artifactId>
    <version>5.0.0-M5</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.junit.vintage</groupId>
    <artifactId>junit-vintage-engine</artifactId>
    <version>4.12.0-M5</version>
    <scope>test</scope>
</dependency>
```

to the `pom.xml`, the IDEA integration uses the project provided version of JUnit 5.

I wonder, if we should update the sample projects to include those runtime dependencies by default -- until the IDE(A) integration is updated.

**Comment by sbrannen** [comment]
> I wonder, if we should update the sample projects to include those runtime dependencies by default -- until the IDE(A) integration is updated.

That's probably a good idea.

@sormuras, I'm reopening this issue and assigning it to you -- OK?

**Comment by paul-hammant** [comment]
@marcphilipp you asked on Twitter what version of Intellij I'm using. Replying here instead:

```
IntelliJ IDEA 2017.1.3
Build #IU-171.4424.56, built on May 12, 2017
```

**Comment by marcphilipp** [comment]
Ok, thanks!

Have you tried the workaround posted by @sormuras?

**Comment by paul-hammant** [comment]
Yes that works, thanks.   As the team adds that section to `<deps/>` it might be best to add the comment line to each of the three, and not just atop the three.

**Comment by sormuras** [comment]
Added additional (M6 launcher and engine) dependencies via https://github.com/junit-team/junit5-samples/commit/f27f666bce935a783e0a0f619d9c74c1bce5b938

**Comment by paul-hammant** [comment]
Thanks - I'll resume testing with M6 :)

**Comment by sormuras** [comment]
> Added additional (M6 launcher and engine) dependencies via https://github.com/junit-team/junit5-samples/commit/f27f666bce935a783e0a0f619d9c74c1bce5b938

Closed again.
