### ISSUE TITLE
compute method on primitive maps cause boxing/unboxing

### ISSUE THREAD

**Issue by gity** [junit-team/junit5-samples#31]
The compute method on the maps require unboxing and boxing since the rely on the standard JDK 8  BiFunction instead of generating primitive type specific a BiFunction for each use case.

**Comment by sormuras** [comment]
> [...] on the maps [...]

Which maps?

But hey, it's sample project where speed is not the first goal. Auto-boxing is okay here.

**Comment by gity** [comment]
For example, [Object2LongMap#computeLong](http://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/objects/Object2LongMap.html#computeLong-K-java.util.function.BiFunction-)

For example compare with [Koloboke ObjLongMap#compute](http://leventov.github.io/Koloboke/api/1.0/java8/com/koloboke/collect/map/ObjLongMap.html#compute-K-com.koloboke.function.ObjLongToLongFunction-)

It good that it is solved with [Object2LongMap#computeLongIfAbsent](http://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/objects/Object2LongMap.html#computeLongIfAbsent-K-java.util.function.ToLongFunction-), shame about computeLong

**Comment by sormuras** [comment]
True.

But where are we using "standard JDK 8 BiFunction" compute methods below https://github.com/junit-team/junit5-samples ?

**Comment by gity** [comment]
sorry I posted against wrong repo
