### ISSUE TITLE
Scope test missing in samples

### ISSUE THREAD

**Issue by snicoll** [junit-team/junit5-samples#32]
This sample does not have a `test`scope for the two last dependencies. 

https://github.com/junit-team/junit5-samples/blob/3fdebd603f448c10413e4780327ccfdb27c15500/junit5-maven-consumer/pom.xml#L85

I am assuming this is an oversight.

**Comment by marcphilipp** [comment]
You're right. Would you mind submitting a PR to fix it? 🙂

**Comment by snicoll** [comment]
Sure
