### ISSUE TITLE
Please provide vanilla samples

### ISSUE THREAD

**Issue by snicoll** [junit-team/junit5-samples#34]
Can you please provide vanilla samples that demonstrates what a user should do to get started with JUnit5 (and only that?). The current sample mixes different concerns and while they are separated from the pom, the changes in JUnit5 are significant enough to deserve a dedicated sample IMO.

The installation section in the documentation is a bit confusing, I am not sure that listing all the jars that the JUnit distribution now ships is the most important information to get started. It then redirects to the two samples (which is why I am creating an issue here).

On a related note, it looks like the Spring Boot project [has a vanilla sample](https://github.com/spring-projects/spring-boot/tree/485d0ed8bed45a46851ed9c286d81977800272a3/spring-boot-samples/spring-boot-sample-junit-jupiter) (at least the build part). Can you please confirm that adding 3 jars manually is what needs to be done?

## Deliverables

- [x] Vanilla Gradle project
- [ ] Vanilla Maven project

**Comment by sormuras** [comment]
"Vanilla" as w/o a build tool? That's probably a good idea. Just some (3, or 4 now) jars and a main and a test class along with some shell scripts to build and execute them.  Structured like:
```
+ deps-compiletime/
  - apiguardian-1.0.0.jar
  - junit-jupiter-api-5.0.0.jar
  - junit-platform-commons-1.0.0.jar
  - opentest4-1.0.0.jar
+ deps-runtime/
  - junit-platform-console-standalone-1.0.0.jar (or each jar needed to launch a test run w/ Jupiter?)
+ src
  + main
    + java
       + foo
          - Foo.java
+ src
  + test
    + java
       + foo
          - FooTests.java
- build.bat
- build.sh
- run.bat
- run.sh
- test.bat
- test.sh
```

Does this sample look more vanilla?

**Comment by snicoll** [comment]
Sorry, no. Vanilla as only showing a plain JUnit5 use case. The current sample shows how you can run your JUnit4 tests and other scenario. I think a sample that shows the "standard case" and only that will help users to understand what they need to get started.

**Comment by sormuras** [comment]
Ah. Remove other code and configuration setup and only leave "[FirstTests.java](https://github.com/junit-team/junit5-samples/blob/master/junit5-maven-consumer/src/test/java/com/example/project/FirstTest.java)"?

**Comment by sormuras** [comment]
And enhance "FirstTests" with more examples from the user-guide?

**Comment by snicoll** [comment]
Split the current sample basically, yes. I think there are users that want to know what it takes to write tests with JUnit5 (and only that). And they are users wondering how they can run their existing tests on the new platform. Right now, the two are combined which brings noise in each scenario. 

I understand that JUnit is more modular and that's awesome but there should be a "shortcut" for the regular case IMO.

**Comment by sormuras** [comment]
JUnit 5 "Jupiter-only" Gradle build script could look like:
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.junit.platform:junit-platform-gradle-plugin:1.0.0'
    }
}

apply plugin: 'java'
apply plugin: 'org.junit.platform.gradle.plugin'

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.0.0'

    testRuntime group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.0.0'
}
```

Now, the `Calculator` _application_ and the `FirstTests` go in `src/[main|test]/java`...

**Comment by sormuras** [comment]
Here are the resolved external dependencies from the minimal Gradle script above, using Intellij IDEA 2017.2.4:

![junit5-vanilla-deps-gradle-idea](https://user-images.githubusercontent.com/2319838/30425232-d0a5f00a-9948-11e7-8d49-b12b0d1c6a83.PNG)

**Comment by snicoll** [comment]
Sorry I am not following why you're pasting this here.

**Comment by sormuras** [comment]
Just to ensure, that we are on the same road regarding what a vanialla sample looks like.

**Comment by snicoll** [comment]
You tell me, I am not an expert in JUnit 5 :) 

That looks Vanilla for Gradle to me even though I am not sure a beginner cares between the `testCompile` and `testRuntime` scope (a single entry would be less noise IMO). Having said that, I can certainly appreciate that the sample uses the right scope (I opened a PR for that myself a few days ago!)

**Comment by sbrannen** [comment]
> You tell me, I am not an expert in JUnit 5 :) 

I can confirm that that's about as _vanilla_ as it gets for JUnit Jupiter and Gradle. 😉 

> That looks Vanilla for Gradle to me even though I am not sure a beginner cares between the `testCompile` and `testRuntime` scope (a single entry would be less noise IMO). Having said that, I can certainly appreciate that the sample uses the right scope (I opened a PR for that myself a few days ago!)

I agree that a beginner probably doesn't care about that, but I also think the JUnit Team should demonstrate the right way to do it (even if it's an additional dependency in the POM or Gradle build script).

**Comment by snicoll** [comment]
> I also think the JUnit Team should demonstrate the right way to do it

I agree, I just wrote that myself. It's a different story for Maven though.

**Comment by sormuras** [comment]
Partly addressed with https://github.com/junit-team/junit5-samples/commit/a98326b55e037dbc933a7a9560dd769e77b68210 using minimal Gradle setup.

**Comment by snicoll** [comment]
Thanks for adding the samples.

As this issue is closed now and I didn't get feedback on the one entry proposal. Can you please confirm that vanilla means I have to manage two versions to get started? You do not foresee another way to handle this for the user?

**Comment by sormuras** [comment]
> [...] It's a different story for Maven though and I still think a single dependency would be better.

Why is a different story? Because there's only "test" scope?

It could be possible to only refer to the "jupiter-engine" artifact and let Maven (and Gradle?) sort out the depedency to "jupiter-api" and all other needed artifacts as well.

**Comment by snicoll** [comment]
> Why is it a different story? Because there's only a "test" scope?

Yes.

**Comment by sormuras** [comment]
Looks like #40 compiles. Will merge the "reduction" PR soon.

Thanks for being patient with me here. :)

**Comment by sormuras** [comment]
With https://github.com/junit-team/junit5-samples/commit/d4441db1f1dd70353e8b7cda884fb6c37175ac17 finally ... pristine Maven vanilla flavor. 🍦
