### ISSUE TITLE
Warnings in Gradle Consumer about API constants

### ISSUE THREAD

**Issue by BlueIce** [junit-team/junit5-samples#45]
Likely due to https://github.com/junit-team/junit5/issues/1065 the build of the Gradle Consumer shows some warnings about unknown API constants. See [Travis Build](https://travis-ci.org/junit-team/junit5-samples/jobs/282719707):

```
Task :compileTestJava
warning: unknown enum constant Status.STABLE
  reason: class file for org.apiguardian.api.API$Status not found
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
6 warnings
```

This might be confusing for someone using the Gradle Consumer as a template.

**Comment by marcphilipp** [comment]
Good catch, thanks!

The workaround is to add `testCompileOnly('org.apiguardian:apiguardian-api:1.0.0')` to `build.gradle`.

@junit-team/junit-lambda Shall we add that to all sample projects?

**Comment by sbrannen** [comment]
> @junit-team/junit-lambda Shall we add that to all sample projects?

👍

**Comment by sbrannen** [comment]
Something like this.... 

https://github.com/sbrannen/junit5-demo/commit/fa6afe6214746b7ebc0e25eedc6f8853d67fc7ba

😉
