### ISSUE TITLE
mvn test command failed

### ISSUE THREAD

**Issue by le93us** [junit-team/junit5-samples#49]
Hello,

can someone help to make simple `junit5` test work?

Here is link to bug-demmo repo.
https://github.com/le93us/junit5-maven-bug

**Comment by sormuras** [comment]
You're missing an engine on your classpath. See https://github.com/junit-team/junit5-samples/blob/master/junit5-vanilla-maven/pom.xml for details.

**Comment by le93us** [comment]
Thank you, @sormuras. You are right.
