### ISSUE TITLE
Store is misused in MockitoExtension

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5-samples#6]
I realize that MockitoExtension should not be considered for production use but the way the ExtensionContext.Store is used isn't a good example of why a Store should be used.  With the existing code, it's possible to return two references to the same object if the same Java class is "injected" into a test method twice.  For instance:

```
@ExtendWith(MockitoExtension.class)
public class MockitoExtensionMisuse {
  
  @Test
  public void testSomethingWithTwoProperties(@InjectMock Properties properties1, @InjectMock Properties properties2) {
    ...
  }

}
```

In the testSomethingWithTwoProperties() method, both properties1 and properties2 will be references to the same instance.

**Comment by sbrannen** [comment]
Resolved in 039d920c7ff9767b4dbc522febb685ede0b5d053.
