### ISSUE TITLE
Update README for junit5-migration-gradle regarding Gradle test task

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5-samples#71]
## Overview

The `README.md` file for the `junit5-migration-gradle` project still documents the use of the `junit-platform-gradle-plugin`; whereas, `build.gradle` has been updated to make use of the built-in support for the JUnit Platform in Gradle 4.6+.

## Deliverables

- [ ] Update the _README_ for `junit5-migration-gradle` regarding the Gradle `test` task.

**Comment by marcphilipp** [comment]
Good catch! Thanks, Sam! 👍
