### ISSUE TITLE
junit5 console launcher doesn't run Junit4 tests

### ISSUE THREAD

**Issue by kb1993** [junit-team/junit5-samples#76]
I've forked this https://github.com/junit-team/junit5-samples/tree/master/junit5-jupiter-starter-ant

I then added a sample Junit4 test under test junit5-jupiter-starter-ant/src/test/java/com/example/project/

Launcher o/p:
Ran the build.sh expecting the vintage engine to show the run o/p.
![image](https://user-images.githubusercontent.com/36759871/42521612-ee95392a-8486-11e8-9af6-b1df8570b2c8.png)

![image](https://user-images.githubusercontent.com/36759871/42521493-abccb9ce-8486-11e8-899b-717eea3460ae.png)
My new class is not being picked by vintage

**Comment by sormuras** [comment]
Thanks for creating this new issue and providing more details.

One more question: what the file/class name of you JUnit 4 test?

**Comment by kb1993** [comment]
@sormuras Thanks for the previous reply.
I've shared the details here.

Could you ple

**Comment by sormuras** [comment]
Okay, the `s` is at the end. If you want to include classes ending with `Test` you need to include them like:

```
        <junitlauncher haltOnFailure="true" printSummary="true">
            <classpath refid="test.classpath"/>
            <testclasses outputdir="build/test-report">
                <fileset dir="build/test">
                    <include name="**/*Tests.class"/>
                    <include name="**/*Test.class"/>
                </fileset>
...
```

Now to the content of `CalculatorJunit4Tests.java`. Can you please post it here, too?

**Comment by sormuras** [comment]
Looks like `<junitlauncher>` is started twice. Could be an issue with the task implementation.

**Comment by kb1993** [comment]
package com.example.project;


import org.junit.Test;
class CalculatortJunit4Tests{
@Test(expected = AssertionError.class)
public void assertErrorOldStyle() 	{throw new AssertionError(); 	}
}

**Comment by sormuras** [comment]
JUnit 3 and 4 classes need to be `public`.

**Comment by kb1993** [comment]
Thanks! Let me try that..but a quick question
Are we not supposed to add the vintage jars for junitlauncher task ? 
How is that working without any

**Comment by sormuras** [comment]
> Are we not supposed to add the vintage jars for junitlauncher task ?

Yes, we are, and we do. Via the JUnit 5 *standalone* distribution "all-deps-are-in" happy jar being copied to the `${ANT_HOME}/lib` directory by the `build.sh` script:

https://github.com/junit-team/junit5-samples/blob/29fd8a57d4fcf5c7490f280e1d9530e78d380d69/junit5-jupiter-starter-ant/build.sh#L20

**Comment by kb1993** [comment]
Great!  Thanks

**Comment by sormuras** [comment]
You're welcome.
