### ISSUE TITLE
Missing assertThrow() / assertDoesNotThrow​() / assertAll() examples

### ISSUE THREAD

**Issue by olibre** [junit-team/junit5-samples#78]
To check exceptions use:

* [`assertAll​()`](https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Assertions.html#assertAll(java.lang.String,java.util.Collection))  
    *Asserts* that *all* supplied `executables` do not throw exceptions.

* [`assertDoesNotThrow​()`](https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Assertions.html#assertDoesNotThrow(org.junit.jupiter.api.function.Executable))  
    *Asserts* that execution of the supplied `executable`/`supplier` *does not throw* any kind of [exception](https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html?is-external=true).

* [`assertThrows​()`](https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Assertions.html#assertThrows(java.lang.Class,org.junit.jupiter.api.function.Executable))  
    *Asserts* that execution of the supplied `executable` *throws* an exception of the `expectedType` and returns the [exception](https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html?is-external=true).

See also my example snippet:  
https://stackoverflow.com/a/51768474/938111

**Comment by marcphilipp** [comment]
Where are examples for these missing from? Except `assertDoesNotThrow​()` they are documented in the user guide.

**Comment by olibre** [comment]
I am sorry, I was thinking this repository junit5-samples aimed to provide examples of each feature.

I have just browsed the files, and I understand now this repository is just to show how to integrate JUnit5 with Ant/Maven/Gradle/...

**Comment by marcphilipp** [comment]
Yes, among other things. Basically a set of projects that you check out to get started with JUnit 5. The most important assertions are documented in https://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions. And there's Javadoc for the `Assertions` class that documents them all: https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Assertions.html#method.summary.

**Comment by altimmons** [comment]
Im gonna have to agree with the original poster.  The syntax for AssertDoesNotThrow clearly differs, yet I've spent the past 2 hours trrying to figure out what the heck it expects from me.  I've tried every combination of Google search term and Lambda./interface notation.

**Comment by altimmons** [comment]
I also have been using this as a source- https://junit.org/junit5/docs/current/user-guide/index.pdf, Ill save you the trouble, the single appearance is on pg 18.  And its in Kotlin.  Which may be exactly like Java.  Or not, I really don't know, so I cant tell if the syntax differs or Kotlin differs.

**Comment by sbrannen** [comment]
@altimmons, you can see a number of examples for `assertDoesNotThrow()` in Java here:

https://github.com/junit-team/junit5/blob/master/junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertDoesNotThrowAssertionsTests.java

If you'd like for examples to be included in the JUnit User Guide, please [create an issue](https://github.com/junit-team/junit5/issues/new/choose) for it.

Thanks
