### ISSUE TITLE
LICENSE.md is missing as well as TOF comment referencing copyright and license

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5-samples#8]
Assuming this project is supposed to have the same licensing as the junit5 project, a copy of LICENSE.md should be placed in the project and the rest of the files should have top-of-file licenses added (I noticed it was missing from junit5-mockito-extension/build.gradle but the TOF license comments are present on many of the Java files I looked at.

**Comment by sbrannen** [comment]
Thanks for bringing this to our attention!
