### ISSUE TITLE
Discrepancy between sample and user guide

### ISSUE THREAD

**Issue by oliviercailloux** [junit-team/junit5-samples#80]
The [user guide](https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven-engines-configure) indicates that both `junit-platform-surefire-provider` and `junit-jupiter-engine` should be dependencies of the `maven-surefire-plugin` plugin, and the code should just depend on `junit-jupiter-api` (for simple cases).

The sample [referenced](https://github.com/junit-team/junit5-samples/blob/r5.2.0/junit5-jupiter-starter-maven/pom.xml) by the user guide rather uses `junit-jupiter-engine` as a global dependency. 

The [current](https://github.com/junit-team/junit5-samples/blob/master/junit5-jupiter-starter-maven/pom.xml) sample depend globally on `junit-jupiter-api`, `junit-jupiter-engine` and `junit-jupiter-params`, and does not mention `junit-platform-surefire-provider` at all. I guess that the supplementary dependency on `junit-jupiter-params` is there because the test is parameterized. But what about the other differences? What is the recommended configuration for a simple project using junit5?

Can you possibly change or comment the sources of information so that they match or we understand why they differ?

**Comment by marcphilipp** [comment]
Thanks for reporting this issue! You're right, this is confusing! There are a few things that require us to change this:

- Surefire 2.22.0 now has native support for the JUnit Platform. Thus, the `junit-platform-surefire-provider` is deprecated and should no longer be used. I'll update the User Guide accordingly.
- While for Maven it's sufficient to declare `junit-jupiter-engine` as a a dependency for the `maven-surefire-plugin`, it's easier to declare it as a normal test dependency (I wish Maven had a `testRuntime` scope) so IDEs will also pick it up. This should also be mentioned in the User Guide.

**Comment by marcphilipp** [comment]
We will update the user guide for 5.3 GA in https://github.com/junit-team/junit5/issues/1535. Thanks again for the feedback!
