### ISSUE TITLE
In the maven sample the junit-jupiter-api dependency is not needed

### ISSUE THREAD

**Issue by matyasf** [junit-team/junit5-samples#85]
Since its a dependency of "junit-jupiter-engine" which is already added as in the project.

See here: https://github.com/junit-team/junit5-samples/blob/6c81972c691a7d055d895953eda5cefead8dc541/junit5-jupiter-starter-maven/pom.xml#L21

**Comment by sormuras** [comment]
A future version of Surefire (3.0.0?) will auto-resolve `junit-jupiter-engine` for when the `junit-jupiter-api` artifact is present. For now, referring to `junit-jupiter-engine` is neccessary. Also referring to `junit-jupiter-api` doesn't hurt -- and is already more future-proof.
