### ISSUE TITLE
Upgrade junit-maven-consumer example to use junit-jupiter and junit-platform.

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5-samples#9]
Currently blocked by https://github.com/junit-team/junit5/issues/286

**Comment by sbrannen** [comment]
How is this _blocked_?

**Comment by sbrannen** [comment]
This was in fact an internal task that was already scheduled to be dealt with (just not listed anywhere publicly), but thanks for pointing it out. 😉 

In any case, I've already performed the necessary upgrades on all sample projects in this repository, so I am closing this issue.

**Comment by smoyer64** [comment]
Two ships passing in the night!

Sorry for the extra chatter ... I didn't know there was an internal list!  I stated this issue was blocked because https://github.com/junit-team/junit5/issues/286 was still open when I wrote the issue.  I assumed that waiting until that issue was closed before completing the work would be better (not knowing you had both taken care of).

**Comment by sbrannen** [comment]
> Two ships passing in the night!

Nice!  Very poetic.

cheers,

Sam
