### ISSUE TITLE
Consider running Bazel sample with Bazelisk

### ISSUE THREAD

**Issue by jbduncan** [junit-team/junit5-samples#93]
I seem to remember that the [JShell-based samples](https://github.com/junit-team/junit5-samples/blob/master/src/Builder.java) were unable to run Bazel because it was difficult to find a way of running Bazel locally on a developer's machine without pre-installing it. However, I've recently learned of a potential solution called [Bazelisk](https://github.com/philwo/bazelisk), which is similar to Gradle's wrapper in that it downloads and installs Bazel at runtime before running Bazel commands.

However, although I think that Bazelisk should be considered, it's worth noting that it currently needs Python to work, but the author has expressed in the README that they may want to write a Go version in the future. So if the JUnit 5 team is interested in using Bazelisk, then I see three options:

1. Require that the user has Python installed to build the samples.
2. See if running Bazelisk on Jython would work.
4. Wait until a Go version or similar is released, eliminating the need to install Python.

I'd love to hear the JUnit 5 team's thoughts regarding all this. :)

**Comment by jbduncan** [comment]
I've renamed the issue after I realised that my phone incorrectly autocorrected "using" to "evening". ;)

**Comment by marcphilipp** [comment]
Ah, that's what you meant... ;-)

Sounds like a good idea! Would you be interested in submitting a PR?

**Comment by jbduncan** [comment]
Sure, I'd be very interested! I probably won't be free until this weekend, but if you're happy to wait then I'll gladly give this a shot.

**Comment by marcphilipp** [comment]
Sure, sounds good! I've assigned you for the time being.

**Comment by jbduncan** [comment]
Cheers @marcphilipp!

I started working on this today, but I quickly noticed that Bazelisk has a bug which I managed to fix locally on my machine and which I'm thinking of raising an issue or PR for soon.

Would you be happy for me to submit a PR to `junit5-samples` with my locally-fixed Bazelisk, or would you prefer that we wait until my fix is merged in?

**Comment by jbduncan** [comment]
Cool, okay!

So far, my currently unpublished solution depends on Python being installed to get Bazelisk running. I did do some coding investigation to use Jython from within the `build-all-samples.jsh`, but it was a bit too complicated for me to suss out earlier this evening.

@marcphilipp Do you have a preference as to whether Python should be pre-installed or not? And if it's too much for me to figure out how to use Jython or a similar solution, what would your thoughts be?

**Comment by jbduncan** [comment]
Oh, I should also say that my Bazelisk bug fix has been merged in, so that's out of the way now. :)

**Comment by marcphilipp** [comment]
I think it's okay to require Python since it's a requirement of Bazelisk. We can worry about making it better later, if need be.

**Comment by jbduncan** [comment]
Great, sounds good to me @marcphilipp! I intend to submit a PR later tonight or tomorrow.
